name: Trigger auto deployment for demo-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-app-AutoDeployTrigger-8647dea0-5fd6-4e92-8986-f1c35b988f18.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ca5bae7f0b92acr.azurecr.io
          registryUsername: ${{ secrets.DEMOAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOAPP_REGISTRY_PASSWORD }}
          containerAppName: demo-app
          resourceGroup: rg-demo-app-01
          imageToBuild: ca5bae7f0b92acr.azurecr.io/demo-app:${{ github.sha }}
          
            

     

