on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
        default: dev
jobs:

  test-cli:
    name: Test CLI
    runs-on: ubuntu-latest

    environment: ${{ inputs.env }}

    steps:
      -  
          name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      -
          name: Azure Cli 
          uses: azure/CLI@v1
          id: get-secrets
          env:
            keyvaultName: 'testkvapozo'
            secretNames: "MongoPassword SQLPassword"
          with:
            inlineScript: |
              chmod +x /tools/utils/scripts/bash/GetSecretsFromKeyVault.sh
              sh ./tools/utils/scripts/bash/GetSecretsFromKeyVault.sh ${{ env.keyvaultName }} ${{ env.secretNames }}
